BLOCKED-COMMANDS:
  - //calc
  - //calculate
  - //eval
  - //evaluate
  - //solve
  - /pl
  - /plugins
  - /?
  - /about
  - /version
  - /bukkit:pl
  - /bukkit:plugins
  - /bukkit:?
  - /ewarp